// import 'dart:developer';
// import 'dart:io';

// //import 'package:ai_health_assistant/screens/chat/chat_bot_screen.dart';
// //import 'package:ai_health_assistant/theme/app_colors.dart';
// import 'package:easytrip/presentation/screens/chat_bot_screen.dart';
// import 'package:flutter/material.dart';
// import 'package:intl/intl.dart';
// import 'package:syncfusion_flutter_pdf/pdf.dart';
// import 'package:path_provider/path_provider.dart';
// import 'package:share_plus/share_plus.dart';
// import 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart';

// // PDF generation
// class HealthReportPDFGenerator {
//   // Helper method to clean text for PDF
//   static String _cleanTextForPdf(String text) {
//     if (text.isEmpty) return text;
    
//     // Remove emojis and special Unicode characters
//     String cleaned = text.replaceAll(RegExp(r'[^\x00-\x7F]'), ''); // Remove non-ASCII
    
//     // Replace common markdown symbols that might cause issues
//     cleaned = cleaned.replaceAll(RegExp(r'\*\*(.*?)\*\*'), r'$1'); // Remove bold markdown
//     cleaned = cleaned.replaceAll(RegExp(r'\*(.*?)\*'), r'$1'); // Remove italic markdown
//     cleaned = cleaned.replaceAll(RegExp(r'#{1,6}\s'), ''); // Remove markdown headers
//     cleaned = cleaned.replaceAll(RegExp(r'•'), '-'); // Replace bullet points
//     cleaned = cleaned.replaceAll(RegExp(r"[^\w\s\-.,!?():\'\/%]"), ''); 
    
//     // Keep only safe characters
    
//     // Clean up multiple spaces and newlines
//     cleaned = cleaned.replaceAll(RegExp(r'\s+'), ' ');
//     cleaned = cleaned.trim();
    
//     return cleaned;
//   }

//   static Future<String> generateHealthReport(HealthAssessment assessment) async {
//     log('Generating PDF health report', name: 'pdfGenerator');

//     try {
//       // Create a new PDF document
//       final PdfDocument document = PdfDocument();
//       final PdfPage page = document.pages.add();
//       final PdfGraphics graphics = page.graphics;

//       // Define fonts and colors - Use TrueType fonts for better character support
//       final PdfFont titleFont = PdfStandardFont(PdfFontFamily.helvetica, 24, style: PdfFontStyle.bold);
//       final PdfFont headerFont = PdfStandardFont(PdfFontFamily.helvetica, 16, style: PdfFontStyle.bold);
//       final PdfFont subHeaderFont = PdfStandardFont(PdfFontFamily.helvetica, 14, style: PdfFontStyle.bold);
//       final PdfFont bodyFont = PdfStandardFont(PdfFontFamily.helvetica, 12);
//       final PdfFont smallFont = PdfStandardFont(PdfFontFamily.helvetica, 10);

//       final PdfColor primaryColor = PdfColor(34, 139, 34); // Green
//       final PdfColor grayColor = PdfColor(128, 128, 128);
//       final PdfColor blackColor = PdfColor(0, 0, 0);

//       double yPosition = 50;
//       const double leftMargin = 50;
//       const double rightMargin = 50;
//       const double pageWidth = 595; // A4 width in points
//       const double contentWidth = pageWidth - leftMargin - rightMargin;

//       // Helper function to add new page if needed
//       PdfPage getCurrentPage() {
//         if (yPosition + 50 > page.getClientSize().height - 50) {
//           final newPage = document.pages.add();
//           yPosition = 50;
//           return newPage;
//         }
//         return page;
//       }

//       PdfGraphics getCurrentGraphics() {
//         return getCurrentPage().graphics;
//       }

//       // Helper function to draw text safely
//       void drawTextSafely(String text, PdfFont font, double x, double y, double width, PdfBrush brush) {
//         try {
//           final cleanText = _cleanTextForPdf(text);
//           if (cleanText.isNotEmpty) {
//             getCurrentGraphics().drawString(
//               cleanText,
//               font,
//               bounds: Rect.fromLTWH(x, y, width, 20),
//               brush: brush,
//             );
//           }
//         } catch (e) {
//           log('Error drawing text: $e, Text: ${text.substring(0, text.length > 50 ? 50 : text.length)}...', name: 'pdfGenerator');
//           // Fallback: draw placeholder text
//           getCurrentGraphics().drawString(
//             '[Content contains unsupported characters]',
//             font,
//             bounds: Rect.fromLTWH(x, y, width, 20),
//             brush: PdfSolidBrush(grayColor),
//           );
//         }
//       }

//       // Header Section
//       graphics.drawRectangle(
//         brush: PdfSolidBrush(primaryColor),
//         bounds: Rect.fromLTWH(0, 0, pageWidth, 80),
//       );

//       graphics.drawString(
//         'HEALTH ASSESSMENT REPORT',
//         titleFont,
//         bounds: Rect.fromLTWH(leftMargin, 20, contentWidth, 30),
//         brush: PdfSolidBrush(PdfColor(255, 255, 255)),
//       );

//       graphics.drawString(
//         'Generated by Dr. Healix AI',
//         bodyFont,
//         bounds: Rect.fromLTWH(leftMargin, 50, contentWidth, 20),
//         brush: PdfSolidBrush(PdfColor(255, 255, 255)),
//       );

//       yPosition = 100;

//       // Report Information Section
//       yPosition += 20;
//       drawTextSafely(
//         'REPORT INFORMATION',
//         headerFont,
//         leftMargin,
//         yPosition,
//         contentWidth,
//         PdfSolidBrush(primaryColor),
//       );

//       yPosition += 25;
//       final reportInfo = [
//         'Report ID: ${_cleanTextForPdf(assessment.id)}',
//         'Assessment Date: ${DateFormat('MMMM dd, yyyy').format(assessment.startDate)}',
//         'Completion Date: ${DateFormat('MMMM dd, yyyy').format(assessment.endDate ?? DateTime.now())}',
//         'Report Generated: ${DateFormat('MMMM dd, yyyy \'at\' HH:mm').format(DateTime.now())}',
//       ];

//       for (final info in reportInfo) {
//         drawTextSafely(info, bodyFont, leftMargin, yPosition, contentWidth, PdfSolidBrush(blackColor));
//         yPosition += 18;
//       }

//       // Patient Information Section
//       yPosition += 20;
//       getCurrentPage(); // Check for new page
      
//       drawTextSafely(
//         'PATIENT INFORMATION',
//         headerFont,
//         leftMargin,
//         yPosition,
//         contentWidth,
//         PdfSolidBrush(primaryColor),
//       );

//       yPosition += 25;
//       final patientInfo = assessment.patientInfo;
//       final patientDetails = [
//         'Age: ${patientInfo['age']?.toString() ?? 'Not specified'}',
//         'Gender: ${_cleanTextForPdf(patientInfo['gender']?.toString() ?? 'Not specified')}',
//         'Additional Info: ${_cleanTextForPdf(patientInfo['raw_info']?.toString() ?? 'None provided')}',
//       ];

//       for (final detail in patientDetails) {
//         getCurrentPage(); // Check for new page
//         drawTextSafely(detail, bodyFont, leftMargin, yPosition, contentWidth, PdfSolidBrush(blackColor));
//         yPosition += 18;
//       }

//       // Symptoms Section
//       yPosition += 20;
//       getCurrentPage();
      
//       drawTextSafely(
//         'REPORTED SYMPTOMS',
//         headerFont,
//         leftMargin,
//         yPosition,
//         contentWidth,
//         PdfSolidBrush(primaryColor),
//       );

//       yPosition += 25;
//       if (assessment.symptoms.isNotEmpty) {
//         for (final symptom in assessment.symptoms) {
//           getCurrentPage();
//           final cleanSymptom = _cleanTextForPdf(symptom);
//           if (cleanSymptom.isNotEmpty) {
//             drawTextSafely('- $cleanSymptom', bodyFont, leftMargin, yPosition, contentWidth, PdfSolidBrush(blackColor));
//             yPosition += 18;
//           }
//         }
//       } else {
//         drawTextSafely(
//           'No specific symptoms reported',
//           bodyFont,
//           leftMargin,
//           yPosition,
//           contentWidth,
//           PdfSolidBrush(grayColor),
//         );
//         yPosition += 18;
//       }

//       // Medical History Section
//       yPosition += 20;
//       getCurrentPage();
      
//       drawTextSafely(
//         'MEDICAL HISTORY',
//         headerFont,
//         leftMargin,
//         yPosition,
//         contentWidth,
//         PdfSolidBrush(primaryColor),
//       );

//       yPosition += 25;
//       if (assessment.medicalHistory.isNotEmpty) {
//         for (final history in assessment.medicalHistory) {
//           final cleanHistory = _cleanTextForPdf(history);
//           if (cleanHistory.isNotEmpty) {
//             // Split long text into multiple lines
//             final lines = _splitTextIntoLines(cleanHistory, bodyFont, contentWidth - 20);
//             for (final line in lines) {
//               getCurrentPage();
//               drawTextSafely('- $line', bodyFont, leftMargin, yPosition, contentWidth, PdfSolidBrush(blackColor));
//               yPosition += 18;
//             }
//           }
//         }
//       } else {
//         drawTextSafely(
//           'No medical history provided',
//           bodyFont,
//           leftMargin,
//           yPosition,
//           contentWidth,
//           PdfSolidBrush(grayColor),
//         );
//         yPosition += 18;
//       }

//       // Assessment Summary Section
//       yPosition += 20;
//       getCurrentPage();
      
//       drawTextSafely(
//         'ASSESSMENT SUMMARY & RECOMMENDATIONS',
//         headerFont,
//         leftMargin,
//         yPosition,
//         contentWidth,
//         PdfSolidBrush(primaryColor),
//       );

//       yPosition += 25;
//       if (assessment.finalDiagnosis != null) {
//         final cleanDiagnosis = _cleanTextForPdf(assessment.finalDiagnosis!);
//         if (cleanDiagnosis.isNotEmpty) {
//           final summaryLines = _splitTextIntoLines(cleanDiagnosis, bodyFont, contentWidth);
//           for (final line in summaryLines) {
//             getCurrentPage();
//             drawTextSafely(line, bodyFont, leftMargin, yPosition, contentWidth, PdfSolidBrush(blackColor));
//             yPosition += 18;
//           }
//         }
//       }

//       // Risk Level Section (if available)
//       if (assessment.riskLevel != null) {
//         yPosition += 20;
//         getCurrentPage();
        
//         drawTextSafely(
//           'RISK ASSESSMENT',
//           headerFont,
//           leftMargin,
//           yPosition,
//           contentWidth,
//           PdfSolidBrush(primaryColor),
//         );

//         yPosition += 25;
//         final cleanRiskLevel = _cleanTextForPdf(assessment.riskLevel!);
//         final riskColor = cleanRiskLevel.toLowerCase().contains('high')
//             ? PdfColor(220, 20, 60) // Red
//             : cleanRiskLevel.toLowerCase().contains('medium')
//                 ? PdfColor(255, 165, 0) // Orange
//                 : PdfColor(34, 139, 34); // Green

//         drawTextSafely(
//           'Risk Level: $cleanRiskLevel',
//           subHeaderFont,
//           leftMargin,
//           yPosition,
//           contentWidth,
//           PdfSolidBrush(riskColor),
//         );
//         yPosition += 25;
//       }

//       // Recommendations Section
//       if (assessment.recommendations.isNotEmpty) {
//         yPosition += 20;
//         getCurrentPage();
        
//         drawTextSafely(
//           'PERSONALIZED RECOMMENDATIONS',
//           headerFont,
//           leftMargin,
//           yPosition,
//           contentWidth,
//           PdfSolidBrush(primaryColor),
//         );

//         yPosition += 25;
//         for (int i = 0; i < assessment.recommendations.length; i++) {
//           final recommendation = _cleanTextForPdf(assessment.recommendations[i]);
//           if (recommendation.isNotEmpty) {
//             getCurrentPage();
//             drawTextSafely(
//               '${i + 1}. $recommendation',
//               bodyFont,
//               leftMargin,
//               yPosition,
//               contentWidth,
//               PdfSolidBrush(blackColor),
//             );
//             yPosition += 20;
//           }
//         }
//       }

//       // Footer/Disclaimer - Always on last page
//       final lastPage = getCurrentPage();
//       yPosition = lastPage.getClientSize().height - 100;
      
//       lastPage.graphics.drawRectangle(
//         brush: PdfSolidBrush(PdfColor(245, 245, 245)),
//         bounds: Rect.fromLTWH(leftMargin, yPosition, contentWidth, 80),
//       );

//       yPosition += 10;
//       lastPage.graphics.drawString(
//         'IMPORTANT DISCLAIMER',
//         subHeaderFont,
//         bounds: Rect.fromLTWH(leftMargin + 10, yPosition, contentWidth - 20, 15),
//         brush: PdfSolidBrush(primaryColor),
//       );

//       yPosition += 20;
//       final disclaimer = 'This health assessment report is generated by AI and is for informational purposes only. '
//           'It does not constitute medical advice, diagnosis, or treatment. Always consult with qualified '
//           'healthcare professionals for medical decisions and treatment plans.';

//       final disclaimerLines = _splitTextIntoLines(disclaimer, smallFont, contentWidth - 20);
//       for (final line in disclaimerLines) {
//         lastPage.graphics.drawString(
//           line,
//           smallFont,
//           bounds: Rect.fromLTWH(leftMargin + 10, yPosition, contentWidth - 20, 12),
//           brush: PdfSolidBrush(blackColor),
//         );
//         yPosition += 14;
//       }

//       // Save the document
//       final List<int> bytes = await document.save();
//       document.dispose();

//       // Save to file
//       final directory = await getApplicationDocumentsDirectory();
//       final file = File('${directory.path}/health_report_${_cleanTextForPdf(assessment.id)}.pdf');
//       await file.writeAsBytes(bytes);

//       log('PDF report generated successfully: ${file.path}', name: 'pdfGenerator');
//       return file.path;

//     } catch (e) {
//       log('Error generating PDF: $e', name: 'pdfGenerator');
//       rethrow;
//     }
//   }

//   static List<String> _splitTextIntoLines(String text, PdfFont font, double maxWidth) {
//     if (text.isEmpty) return [];
    
//     final words = text.split(' ');
//     final lines = <String>[];
//     String currentLine = '';

//     for (final word in words) {
//       final testLine = currentLine.isEmpty ? word : '$currentLine $word';
      
//       try {
//         final textSize = font.measureString(testLine);
        
//         if (textSize.width <= maxWidth) {
//           currentLine = testLine;
//         } else {
//           if (currentLine.isNotEmpty) {
//             lines.add(currentLine);
//             currentLine = word;
//           } else {
//             // Word is too long, split it
//             if (word.length > 50) {
//               lines.add(word.substring(0, 50));
//               currentLine = word.substring(50);
//             } else {
//               lines.add(word);
//             }
//           }
//         }
//       } catch (e) {
//         // If measuring fails, just add the current line and continue
//         if (currentLine.isNotEmpty) {
//           lines.add(currentLine);
//         }
//         currentLine = word;
//       }
//     }

//     if (currentLine.isNotEmpty) {
//       lines.add(currentLine);
//     }

//     return lines;
//   }
// }

// // PDF viewer screen
// class PDFViewerScreen extends StatelessWidget {
//   final String filePath;
//   final String title;

//   const PDFViewerScreen({
//     super.key,
//     required this.filePath,
//     required this.title,
//   });

//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       appBar: AppBar(
//       //  backgroundColor: AppColors.primaryGreen,
//         title: Text(
//           title,
//           style: const TextStyle(color: Colors.white),
//         ),
//         leading: IconButton(
//           icon: const Icon(Icons.arrow_back, color: Colors.white),
//           onPressed: () => Navigator.pop(context),
//         ),
//         actions: [
//           IconButton(
//             icon: const Icon(Icons.share, color: Colors.white),
//             onPressed: () => _shareReport(context),
//           ),
//         ],
//       ),
//       body: SfPdfViewer.file(
//         File(filePath),
//         onDocumentLoadFailed: (PdfDocumentLoadFailedDetails details) {
//           ScaffoldMessenger.of(context).showSnackBar(
//             SnackBar(
//               content: Text('Failed to load PDF: ${details.error}'),
//               backgroundColor: Colors.red,
//             ),
//           );
//         },
//       ),
//     );
//   }

//   void _shareReport(BuildContext context) async {
//     try {
//       await Share.shareXFiles(
//         [XFile(filePath)],
//         text: 'Health Assessment Report generated by Dr. Healix AI',
//         subject: 'Health Assessment Report',
//       );
//     } catch (e) {
//       ScaffoldMessenger.of(context).showSnackBar(
//         SnackBar(
//           content: Text('Error sharing report: $e'),
//           backgroundColor: Colors.red,
//         ),
//       );
//     }
//   }
// }