import 'dart:developer';
import 'dart:io';
import 'package:easytrip/presentation/screens/chat_bot_screen.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:syncfusion_flutter_pdf/pdf.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart';

// PDF generation for Trip Plans
class TripPlanPDFGenerator {
  // Helper method to clean text for PDF
  static String _cleanTextForPdf(String text) {
    if (text.isEmpty) return text;
    
    // Remove emojis and special Unicode characters
    String cleaned = text.replaceAll(RegExp(r'[^\x00-\x7F]'), ''); // Remove non-ASCII
    
    // Replace common markdown symbols that might cause issues
    cleaned = cleaned.replaceAll(RegExp(r'\*\*(.*?)\*\*'), r'$1'); // Remove bold markdown
    cleaned = cleaned.replaceAll(RegExp(r'\*(.*?)\*'), r'$1'); // Remove italic markdown
    cleaned = cleaned.replaceAll(RegExp(r'#{1,6}\s'), ''); // Remove markdown headers
    cleaned = cleaned.replaceAll(RegExp(r'•'), '-'); // Replace bullet points
    cleaned = cleaned.replaceAll(RegExp(r"[^\w\s\-.,!?():\'\/%]"), ''); 
    
    // Keep only safe characters
    
    // Clean up multiple spaces and newlines
    cleaned = cleaned.replaceAll(RegExp(r'\s+'), ' ');
    cleaned = cleaned.trim();
    
    return cleaned;
  }

  static Future<String> generateTripPlan(TripAssessment assessment) async {
    log('Generating PDF trip plan', name: 'pdfGenerator');

    try {
      // Create a new PDF document
      final PdfDocument document = PdfDocument();
      final PdfPage page = document.pages.add();
      final PdfGraphics graphics = page.graphics;

      // Define fonts and colors - Use TrueType fonts for better character support
      final PdfFont titleFont = PdfStandardFont(PdfFontFamily.helvetica, 24, style: PdfFontStyle.bold);
      final PdfFont headerFont = PdfStandardFont(PdfFontFamily.helvetica, 16, style: PdfFontStyle.bold);
      final PdfFont subHeaderFont = PdfStandardFont(PdfFontFamily.helvetica, 14, style: PdfFontStyle.bold);
      final PdfFont bodyFont = PdfStandardFont(PdfFontFamily.helvetica, 12);
      final PdfFont smallFont = PdfStandardFont(PdfFontFamily.helvetica, 10);

      final PdfColor primaryColor = PdfColor(34, 139, 34); // Green
      final PdfColor accentColor = PdfColor(70, 130, 180); // Steel Blue
      final PdfColor grayColor = PdfColor(128, 128, 128);
      final PdfColor blackColor = PdfColor(0, 0, 0);

      double yPosition = 50;
      const double leftMargin = 50;
      const double rightMargin = 50;
      const double pageWidth = 595; // A4 width in points
      const double contentWidth = pageWidth - leftMargin - rightMargin;

      // Helper function to add new page if needed
      PdfPage getCurrentPage() {
        if (yPosition + 50 > page.getClientSize().height - 50) {
          final newPage = document.pages.add();
          yPosition = 50;
          return newPage;
        }
        return page;
      }

      PdfGraphics getCurrentGraphics() {
        return getCurrentPage().graphics;
      }

      // Helper function to draw text safely
      void drawTextSafely(String text, PdfFont font, double x, double y, double width, PdfBrush brush) {
        try {
          final cleanText = _cleanTextForPdf(text);
          if (cleanText.isNotEmpty) {
            getCurrentGraphics().drawString(
              cleanText,
              font,
              bounds: Rect.fromLTWH(x, y, width, 20),
              brush: brush,
            );
          }
        } catch (e) {
          log('Error drawing text: $e, Text: ${text.substring(0, text.length > 50 ? 50 : text.length)}...', name: 'pdfGenerator');
          // Fallback: draw placeholder text
          getCurrentGraphics().drawString(
            '[Content contains unsupported characters]',
            font,
            bounds: Rect.fromLTWH(x, y, width, 20),
            brush: PdfSolidBrush(grayColor),
          );
        }
      }

      // Header Section with travel theme
      graphics.drawRectangle(
        brush: PdfSolidBrush(primaryColor),
        bounds: Rect.fromLTWH(0, 0, pageWidth, 80),
      );

      graphics.drawString(
        'PERSONALIZED TRIP ITINERARY',
        titleFont,
        bounds: Rect.fromLTWH(leftMargin, 15, contentWidth, 30),
        brush: PdfSolidBrush(PdfColor(255, 255, 255)),
      );

      graphics.drawString(
        'Generated by Smart Trip Planner AI',
        bodyFont,
        bounds: Rect.fromLTWH(leftMargin, 50, contentWidth, 20),
        brush: PdfSolidBrush(PdfColor(255, 255, 255)),
      );

      yPosition = 100;

      // Trip Information Section
      yPosition += 20;
      drawTextSafely(
        'TRIP INFORMATION',
        headerFont,
        leftMargin,
        yPosition,
        contentWidth,
        PdfSolidBrush(primaryColor),
      );

      yPosition += 25;
      final tripInfo = [
        'Trip ID: ${_cleanTextForPdf(assessment.id)}',
        'Planning Started: ${DateFormat('MMMM dd, yyyy').format(assessment.startDate)}',
        'Planning Completed: ${DateFormat('MMMM dd, yyyy').format(assessment.endDate ?? DateTime.now())}',
        'Itinerary Generated: ${DateFormat('MMMM dd, yyyy \'at\' HH:mm').format(DateTime.now())}',
        'Completion Status: ${assessment.isCompleted ? "Complete" : "In Progress"}',
      ];

      for (final info in tripInfo) {
        drawTextSafely(info, bodyFont, leftMargin, yPosition, contentWidth, PdfSolidBrush(blackColor));
        yPosition += 18;
      }

      // Destinations Section
      yPosition += 20;
      getCurrentPage(); // Check for new page
      
      drawTextSafely(
        'DESTINATIONS & TRAVEL SCOPE',
        headerFont,
        leftMargin,
        yPosition,
        contentWidth,
        PdfSolidBrush(primaryColor),
      );

      yPosition += 25;
      final destinationsData = assessment.tripData['destinations'] as Map<String, dynamic>?;
      if (destinationsData != null) {
        final rawResponse = destinationsData['raw_response']?.toString() ?? 'Not specified';
        final destinationLines = _splitTextIntoLines(_cleanTextForPdf(rawResponse), bodyFont, contentWidth);
        for (final line in destinationLines) {
          getCurrentPage();
          drawTextSafely(line, bodyFont, leftMargin, yPosition, contentWidth, PdfSolidBrush(blackColor));
          yPosition += 18;
        }
      } else {
        drawTextSafely(
          'Destination information not yet provided',
          bodyFont,
          leftMargin,
          yPosition,
          contentWidth,
          PdfSolidBrush(grayColor),
        );
        yPosition += 18;
      }

      // Travel Details Section
      yPosition += 20;
      getCurrentPage();
      
      drawTextSafely(
        'TRAVEL DETAILS',
        headerFont,
        leftMargin,
        yPosition,
        contentWidth,
        PdfSolidBrush(primaryColor),
      );

      yPosition += 25;
      final travelDetailsData = assessment.tripData['travelDetails'] as Map<String, dynamic>?;
      if (travelDetailsData != null) {
        final details = travelDetailsData['details']?.toString() ?? 'Not specified';
        final detailLines = _splitTextIntoLines(_cleanTextForPdf(details), bodyFont, contentWidth);
        for (final line in detailLines) {
          getCurrentPage();
          drawTextSafely(line, bodyFont, leftMargin, yPosition, contentWidth, PdfSolidBrush(blackColor));
          yPosition += 18;
        }
      } else {
        drawTextSafely(
          'Travel details not yet provided',
          bodyFont,
          leftMargin,
          yPosition,
          contentWidth,
          PdfSolidBrush(grayColor),
        );
        yPosition += 18;
      }

      // Budget & Preferences Section
      yPosition += 20;
      getCurrentPage();
      
      drawTextSafely(
        'BUDGET & ACCOMMODATION PREFERENCES',
        headerFont,
        leftMargin,
        yPosition,
        contentWidth,
        PdfSolidBrush(primaryColor),
      );

      yPosition += 25;
      final budgetData = assessment.tripData['budget'] as Map<String, dynamic>?;
      if (budgetData != null) {
        final budgetDetails = budgetData['details']?.toString() ?? 'Not specified';
        final budgetLines = _splitTextIntoLines(_cleanTextForPdf(budgetDetails), bodyFont, contentWidth);
        for (final line in budgetLines) {
          getCurrentPage();
          drawTextSafely(line, bodyFont, leftMargin, yPosition, contentWidth, PdfSolidBrush(blackColor));
          yPosition += 18;
        }
      } else {
        drawTextSafely(
          'Budget preferences not yet provided',
          bodyFont,
          leftMargin,
          yPosition,
          contentWidth,
          PdfSolidBrush(grayColor),
        );
        yPosition += 18;
      }

      // Interests & Activities Section
      yPosition += 20;
      getCurrentPage();
      
      drawTextSafely(
        'INTERESTS & PREFERRED ACTIVITIES',
        headerFont,
        leftMargin,
        yPosition,
        contentWidth,
        PdfSolidBrush(primaryColor),
      );

      yPosition += 25;
      final interests = assessment.tripData['interests'] as List<dynamic>?;
      final interestsRaw = assessment.tripData['interests_raw']?.toString();
      
      if (interests != null && interests.isNotEmpty) {
        drawTextSafely(
          'Identified Interests:',
          subHeaderFont,
          leftMargin,
          yPosition,
          contentWidth,
          PdfSolidBrush(accentColor),
        );
        yPosition += 20;
        
        for (final interest in interests) {
          getCurrentPage();
          drawTextSafely('- ${_cleanTextForPdf(interest.toString())}', bodyFont, leftMargin, yPosition, contentWidth, PdfSolidBrush(blackColor));
          yPosition += 16;
        }
        
        if (interestsRaw != null && interestsRaw.isNotEmpty) {
          yPosition += 10;
          drawTextSafely(
            'Detailed Preferences:',
            subHeaderFont,
            leftMargin,
            yPosition,
            contentWidth,
            PdfSolidBrush(accentColor),
          );
          yPosition += 20;
          
          final interestLines = _splitTextIntoLines(_cleanTextForPdf(interestsRaw), bodyFont, contentWidth);
          for (final line in interestLines) {
            getCurrentPage();
            drawTextSafely(line, bodyFont, leftMargin, yPosition, contentWidth, PdfSolidBrush(blackColor));
            yPosition += 18;
          }
        }
      } else {
        drawTextSafely(
          'Activity preferences not yet provided',
          bodyFont,
          leftMargin,
          yPosition,
          contentWidth,
          PdfSolidBrush(grayColor),
        );
        yPosition += 18;
      }

      // User Responses Summary Section
      yPosition += 20;
      getCurrentPage();
      
      drawTextSafely(
        'PLANNING RESPONSES SUMMARY',
        headerFont,
        leftMargin,
        yPosition,
        contentWidth,
        PdfSolidBrush(primaryColor),
      );

      yPosition += 25;
      if (assessment.responses.isNotEmpty) {
        for (final entry in assessment.responses.entries) {
          getCurrentPage();
          
          final stepTitle = _getStepTitle(entry.key);
          drawTextSafely(
            stepTitle,
            subHeaderFont,
            leftMargin,
            yPosition,
            contentWidth,
            PdfSolidBrush(accentColor),
          );
          yPosition += 20;
          
          final responseLines = _splitTextIntoLines(_cleanTextForPdf(entry.value), bodyFont, contentWidth - 20);
          for (final line in responseLines) {
            getCurrentPage();
            drawTextSafely(line, bodyFont, leftMargin + 10, yPosition, contentWidth - 10, PdfSolidBrush(blackColor));
            yPosition += 16;
          }
          yPosition += 10;
        }
      }

      // Generated Itinerary Section
      if (assessment.finalItinerary != null && assessment.finalItinerary!.isNotEmpty) {
        yPosition += 20;
        getCurrentPage();
        
        drawTextSafely(
          'YOUR PERSONALIZED ITINERARY',
          headerFont,
          leftMargin,
          yPosition,
          contentWidth,
          PdfSolidBrush(primaryColor),
        );

        yPosition += 25;
        final cleanItinerary = _cleanTextForPdf(assessment.finalItinerary!);
        if (cleanItinerary.isNotEmpty) {
          final itineraryLines = _splitTextIntoLines(cleanItinerary, bodyFont, contentWidth);
          for (final line in itineraryLines) {
            getCurrentPage();
            drawTextSafely(line, bodyFont, leftMargin, yPosition, contentWidth, PdfSolidBrush(blackColor));
            yPosition += 16;
          }
        }
      }

      // Recommendations Section
      if (assessment.recommendations.isNotEmpty) {
        yPosition += 20;
        getCurrentPage();
        
        drawTextSafely(
          'ADDITIONAL RECOMMENDATIONS',
          headerFont,
          leftMargin,
          yPosition,
          contentWidth,
          PdfSolidBrush(primaryColor),
        );

        yPosition += 25;
        for (int i = 0; i < assessment.recommendations.length; i++) {
          final recommendation = _cleanTextForPdf(assessment.recommendations[i]);
          if (recommendation.isNotEmpty) {
            getCurrentPage();
            drawTextSafely(
              '${i + 1}. $recommendation',
              bodyFont,
              leftMargin,
              yPosition,
              contentWidth,
              PdfSolidBrush(blackColor),
            );
            yPosition += 20;
          }
        }
      }

      // Trip Planning Tips Section
      yPosition += 20;
      getCurrentPage();
      
      drawTextSafely(
        'TRAVEL PLANNING TIPS',
        headerFont,
        leftMargin,
        yPosition,
        contentWidth,
        PdfSolidBrush(primaryColor),
      );

      yPosition += 25;
      final travelTips = [
        'Book accommodations and flights early for better rates',
        'Check visa requirements and passport validity',
        'Research local customs and cultural etiquette',
        'Pack appropriate clothing for the season and activities',
        'Inform your bank about travel plans to avoid card blocks',
        'Make copies of important documents',
        'Consider travel insurance for peace of mind',
        'Download offline maps and translation apps',
        'Keep emergency contacts and embassy information handy',
        'Stay flexible - some of the best experiences are unplanned!',
      ];

      for (final tip in travelTips) {
        getCurrentPage();
        drawTextSafely('- $tip', bodyFont, leftMargin, yPosition, contentWidth, PdfSolidBrush(blackColor));
        yPosition += 18;
      }

      // Footer/Disclaimer - Always on last page
      final lastPage = getCurrentPage();
      yPosition = lastPage.getClientSize().height - 120;
      
      lastPage.graphics.drawRectangle(
        brush: PdfSolidBrush(PdfColor(245, 245, 245)),
        bounds: Rect.fromLTWH(leftMargin, yPosition, contentWidth, 100),
      );

      yPosition += 10;
      lastPage.graphics.drawString(
        'TRAVEL DISCLAIMER & NOTES',
        subHeaderFont,
        bounds: Rect.fromLTWH(leftMargin + 10, yPosition, contentWidth - 20, 15),
        brush: PdfSolidBrush(primaryColor),
      );

      yPosition += 20;
      final disclaimer = 'This travel itinerary is generated by AI and is for planning purposes only. '
          'Always verify current travel restrictions, visa requirements, and local conditions. '
          'Prices, availability, and regulations may change. The AI recommendations are suggestions '
          'and should be researched and confirmed before booking. Travel at your own discretion and '
          'ensure adequate travel insurance coverage.';

      final disclaimerLines = _splitTextIntoLines(disclaimer, smallFont, contentWidth - 20);
      for (final line in disclaimerLines) {
        lastPage.graphics.drawString(
          line,
          smallFont,
          bounds: Rect.fromLTWH(leftMargin + 10, yPosition, contentWidth - 20, 12),
          brush: PdfSolidBrush(blackColor),
        );
        yPosition += 14;
      }

      // Footer info
      yPosition += 10;
      lastPage.graphics.drawString(
        'Happy travels! - Smart Trip Planner AI',
        smallFont,
        bounds: Rect.fromLTWH(leftMargin + 10, yPosition, contentWidth - 20, 12),
        brush: PdfSolidBrush(accentColor),
      );

      // Save the document
      final List<int> bytes = await document.save();
      document.dispose();

      // Save to file
      final directory = await getApplicationDocumentsDirectory();
      final file = File('${directory.path}/trip_plan_${_cleanTextForPdf(assessment.id)}.pdf');
      await file.writeAsBytes(bytes);

      log('PDF trip plan generated successfully: ${file.path}', name: 'pdfGenerator');
      return file.path;

    } catch (e) {
      log('Error generating PDF: $e', name: 'pdfGenerator');
      rethrow;
    }
  }

  static String _getStepTitle(String stepKey) {
    switch (stepKey) {
      case 'destinations':
        return 'Destinations & Travel Scope:';
      case 'travel_details':
        return 'Travel Details & Group Information:';
      case 'budget_preferences':
        return 'Budget & Accommodation Preferences:';
      case 'interests_activities':
        return 'Interests & Activity Preferences:';
      case 'summary':
        return 'Final Summary:';
      default:
        return '${stepKey.toUpperCase()}:';
    }
  }

  static List<String> _splitTextIntoLines(String text, PdfFont font, double maxWidth) {
    if (text.isEmpty) return [];
    
    final words = text.split(' ');
    final lines = <String>[];
    String currentLine = '';

    for (final word in words) {
      final testLine = currentLine.isEmpty ? word : '$currentLine $word';
      
      try {
        final textSize = font.measureString(testLine);
        
        if (textSize.width <= maxWidth) {
          currentLine = testLine;
        } else {
          if (currentLine.isNotEmpty) {
            lines.add(currentLine);
            currentLine = word;
          } else {
            // Word is too long, split it
            if (word.length > 50) {
              lines.add(word.substring(0, 50));
              currentLine = word.substring(50);
            } else {
              lines.add(word);
            }
          }
        }
      } catch (e) {
        // If measuring fails, just add the current line and continue
        if (currentLine.isNotEmpty) {
          lines.add(currentLine);
        }
        currentLine = word;
      }
    }

    if (currentLine.isNotEmpty) {
      lines.add(currentLine);
    }

    return lines;
  }
}

// PDF viewer screen for trip plans
class TripPlanPDFViewerScreen extends StatelessWidget {
  final String filePath;
  final String title;

  const TripPlanPDFViewerScreen({
    super.key,
    required this.filePath,
    required this.title,
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
       // backgroundColor: AppColors.primaryGreen,
        title: Text(
          title,
          style: const TextStyle(color: Colors.white),
        ),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Colors.white),
          onPressed: () => Navigator.pop(context),
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.share, color: Colors.white),
            onPressed: () => _shareReport(context),
            tooltip: 'Share Trip Plan',
          ),
          IconButton(
            icon: const Icon(Icons.download, color: Colors.white),
            onPressed: () => _showSaveOptions(context),
            tooltip: 'Save Options',
          ),
        ],
      ),
      body: SfPdfViewer.file(
        File(filePath),
        onDocumentLoadFailed: (PdfDocumentLoadFailedDetails details) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Failed to load PDF: ${details.error}'),
              backgroundColor: Colors.red,
            ),
          );
        },
      ),
    );
  }

  void _shareReport(BuildContext context) async {
    try {
      await Share.shareXFiles(
        [XFile(filePath)],
        text: 'My personalized trip itinerary generated by Smart Trip Planner AI',
        subject: 'My Trip Itinerary',
      );
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Error sharing trip plan: $e'),
          backgroundColor: Colors.red,
        ),
      );
    }
  }

  void _showSaveOptions(BuildContext context) {
    showModalBottomSheet(
      context: context,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (context) => Container(
        padding: const EdgeInsets.symmetric(vertical: 20),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Text(
              'Trip Plan Options',
              style: TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 20),
            ListTile(
             // leading: const Icon(Icons.share, color: AppColors.primaryGreen),
              title: const Text('Share Trip Plan'),
              subtitle: const Text('Share with friends and family'),
              onTap: () {
                Navigator.pop(context);
                _shareReport(context);
              },
            ),
            ListTile(
             // leading: const Icon(Icons.print, color: AppColors.primaryGreen),
              title: const Text('Print Trip Plan'),
              subtitle: const Text('Print physical copy'),
              onTap: () {
                Navigator.pop(context);
                _showPrintInfo(context);
              },
            ),
            ListTile(
             // leading: const Icon(Icons.cloud_upload, color: AppColors.primaryGreen),
              title: const Text('Save to Cloud'),
              subtitle: const Text('Coming soon'),
              enabled: false,
              onTap: null,
            ),
          ],
        ),
      ),
    );
  }

  void _showPrintInfo(BuildContext context) {
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('Use your device\'s print function from the share menu'),
        duration: Duration(seconds: 3),
      ),
    );
  }
}